[package]
name = "surrealdb-tool-tester"
version = "0.1.0"
edition = "2021"
description = "Interactive SurrealDB Tool Tester"

[dependencies]
luts-core = { path = "crates/luts-core" }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[bin]]
name = "surrealdb-tool-tester"
path = "examples/tool_tester.rs"